name: Mukund's Blog 
markdown: redcarpet
highliter: pygments

# My configurations

url: http://localhost:4000
foundation-dev-mode: true

# This is where I write my "series of blog meta data"
series-config: _series.yml

Social:
  share:
    facebook:
      appid: 640849809282983
      layout: button_count
      font: arial
      faces: false
      width: 90

sass:
  sass_dir: _sass



 
