name: Mukund's Blog 
markdown: redcarpet
pygments: true

# My configurations

url: http://localhost:4000/
foundation-dev-mode: true

# This is where I write my "series of blog meta data"
series-config: _series.yml
